name: riverpod_boilerplate
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.0.3
  state_notifier: ^1.0.0
  equatable: ^2.0.5
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  iconsax_plus: ^1.0.0
  go_router: ^14.0.2
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    # lottie: true
  assets:
    outputs:
      class_name: RiverpodAssets
  fonts:
    outputs:
      class_name: RiverpodFonts


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular-300.otf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular-400.otf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Regular-500.otf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular-600.otf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Regular-700.otf
          weight: 700

