import 'package:flutter/material.dart';
import 'package:riverpod_boilerplate/shared/themes/app_colors.dart';

class AppInputDecoration extends InputDecoration {
  AppInputDecoration({
    required BuildContext context,
    super.icon,
    super.iconColor,
    super.label,
    super.labelText,
    super.labelStyle,
    super.floatingLabelStyle,
    super.helperText,
    super.helperStyle,
    super.helperMaxLines,
    super.hintText,
    super.hintTextDirection,
    super.hintMaxLines,
    super.errorText,
    super.errorMaxLines,
    super.floatingLabelBehavior,
    super.floatingLabelAlignment,
    super.isCollapsed = false,
    super.isDense,
    super.contentPadding =
        const EdgeInsets.symmetric(vertical: 0, horizontal: 12),
    super.prefixIcon,
    super.prefixIconConstraints,
    super.prefix,
    super.prefixText,
    super.prefixStyle,
    super.prefixIconColor,
    super.suffixIcon,
    super.suffix,
    super.suffixText,
    super.suffixStyle,
    super.suffixIconColor,
    super.suffixIconConstraints,
    super.counter,
    super.counterText,
    super.counterStyle,
    super.focusColor,
    super.hoverColor,
    super.errorBorder,
    super.focusedBorder,
    super.focusedErrorBorder,
    super.disabledBorder,
    super.enabled = true,
    super.semanticCounterText,
    super.alignLabelWithHint = true,
    super.constraints,
  }) : super(
          fillColor: AppColors.lighterGrey,
          filled: true,
          border: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.transparent, width: 0),
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
          enabledBorder: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.transparent, width: 0),
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
          hintStyle: Theme.of(context).textTheme.bodyMedium,
          errorStyle: Theme.of(context).textTheme.labelSmall,
        );
}
